services:
  frontend:
    image: ghcr.io/{{ steps.owner.outputs.OWNER }}/flashcardz-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - web
      - backend
    restart: unless-stopped

  web:
    image: ghcr.io/${{ steps.owner.outputs.OWNER }}/flashcardz-web:latest
    expose:
      - "3000"
    restart: unless-stopped

  backend:
    image: ghcr.io/${{ steps.owner.outputs.OWNER }}/flashcardz-backend:latest
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped
