services:
  frontend:
    image: ghcr.io/amillionhornets/flashcardz-frontend:latest
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/amillionhornets/flashcardz-backend:latest
    container_name: fastapi-backend
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped